name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '36 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch latest data
      run: |-
        curl https://overpass-api.de/api/interpreter?data=%0A%5Bout%3Ajson%5D%5Btimeout%3A25000%5D%3B%0A%28%0A%20%20node%5B%22amenity%22%3D%22post_office%22%5D%28-90%2C%20-180%2C%2090%2C%200%29%3B%0A%20%20way%5B%22amenity%22%3D%22post_office%22%5D%28-90%2C%20-180%2C%2090%2C%200%29%3B%0A%20%20relation%5B%22amenity%22%3D%22post_office%22%5D%28-90%2C%20-180%2C%2090%2C%200%29%3B%0A%29%3B%0Aout%20body%3B%0A%3E%3B%0Aout%20skel%20qt%3B | jq . > post_offices-usa-canada-south-america.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
